# -*- coding: utf-8 -*-
"""MongoDbCRUD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQrJsfAXAIDlSw-s1L-pI_yz470NYHz6
"""

from pymongo import MongoClient

Dbobj=MongoClient("mongodb://NIfnMKrLsGM4KIbf:NIfnMKrLsGM4KIbf@ac-pzzgpjn-shard-00-00.tjmiorw.mongodb.net:27017,ac-pzzgpjn-shard-00-01.tjmiorw.mongodb.net:27017,ac-pzzgpjn-shard-00-02.tjmiorw.mongodb.net:27017/?ssl=true&replicaSet=atlas-6qnxx7-shard-0&authSource=admin&retryWrites=true&w=majority")

Task=Dbobj["Task2"]

Telephoneobj=Task["Telephone"]

X={"name":"Kesavan","Phone Number":"1234567890","Place":"Madurai"}

Telephoneobj.insert_one(X)

A={"name":"Sara","Phone Number":"5434567890","Place":"Kovai"}
B={"name":"Lucky","Phone Number":"7834567890","Place":"London"}

Telephoneobj.insert_many([A,B])

Telephoneobj.update_one(A,"Place":"Chennai")

Telephoneobj.updateMany(
   { "Place": { "$eq": "Chennai" } },
   {
     "$set": { "name": "ASi", "Phone Number": "56655626524" }
     
   }
)

Telephoneobj.deleteOne( {"name": "ASi" } )